### ISSUE TITLE
No Win Animation

### ISSUE THREAD

**Issue by swhalley** [peidevs/Scooter#4]
There should be a win animation for each theme. With the first iteration of scooter, there was a win animation that had some form of animation (spinning eyes) to indicate the winner.

**Comment by swhalley** [comment]
Added Win animation for the scooter theme. Need to do more with the other themes

**Comment by evanepio** [comment]
Win animation for Sticky Note theme can be found in Pull Request #18.

**Comment by swhalley** [comment]
awesome job on the sticky note theme
