### ISSUE TITLE
Lose Animation

### ISSUE THREAD

**Issue by swhalley** [peidevs/Scooter#9]
In the old Dojo version of the application, when a player lost an animation played while the "ball" was hidden. Would be nice to add this animation back for each theme

**Comment by evanepio** [comment]
Pull request #18 partially solves this. It will only have one of the animations. Classic Dojo Scooter randomly chooses from 2. The Sticky Note theme gets an animation for winning and losing. But did not touch PEI Devs theme.

**Comment by swhalley** [comment]
good work. closing
